# Generated by Django 6.0 on 2025-12-14 03:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('letters', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField(blank=True)),
                ('icon', models.CharField(blank=True, help_text='Optional icon name/URL for UI.', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='topics_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='LetterTopicVote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('letter_concept', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topic_votes', to='letters.letterconcept')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='topic_votes', to=settings.AUTH_USER_MODEL)),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topic_votes', to='topics.topic')),
            ],
            options={
                'unique_together': {('user', 'letter_concept', 'topic')},
            },
        ),
        migrations.CreateModel(
            name='LetterTopic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vote_count', models.PositiveIntegerField(default=0)),
                ('consensus_ratio', models.FloatField(default=0.0, help_text='0–1; rough consensus measure.')),
                ('letter_concept', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='letter_topics', to='letters.letterconcept')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='letter_topics', to='topics.topic')),
            ],
            options={
                'unique_together': {('letter_concept', 'topic')},
            },
        ),
    ]
