# Generated by Django 6.0 on 2025-12-14 05:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('people', '0002_remove_person_email_remove_person_has_opt_in_postal_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParticipantProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_verified', models.BooleanField(default=False)),
                ('postal_address_line1', models.CharField(blank=True, max_length=255)),
                ('postal_city', models.CharField(blank=True, max_length=255)),
                ('postal_state', models.CharField(blank=True, max_length=255)),
                ('postal_postcode', models.CharField(blank=True, max_length=20)),
                ('postal_country', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('claimed_person', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='profiles', to='people.person')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
