# Generated by Django 6.0 on 2025-12-14 03:28

import django.db.models.deletion
import letters.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('people', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LetterConcept',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255)),
                ('description', models.TextField(blank=True)),
                ('write_prompt', models.TextField(blank=True, help_text='Optional guidance or script for people writing this letter.')),
                ('origin_city', models.CharField(blank=True, max_length=255)),
                ('origin_region', models.CharField(blank=True, max_length=255)),
                ('origin_state', models.CharField(blank=True, max_length=255)),
                ('destination_city', models.CharField(blank=True, max_length=255)),
                ('destination_region', models.CharField(blank=True, max_length=255)),
                ('destination_state', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='letter_concepts_created', to=settings.AUTH_USER_MODEL)),
                ('created_for', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='letter_concepts', to='people.person')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LetterInstance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(default=letters.models.generate_letter_code, help_text='Short ID printed on the letter and encoded in QR.', max_length=32, unique=True)),
                ('current_city', models.CharField(blank=True, max_length=255)),
                ('current_region', models.CharField(blank=True, max_length=255)),
                ('current_state', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(choices=[('created', 'Created'), ('waiting', 'Waiting for carrier'), ('traveling', 'Traveling'), ('left', 'Left at location'), ('delivered', 'Delivered'), ('archived', 'Archived')], default='created', max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('concept', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='instances', to='letters.letterconcept')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='letter_instances_created', to=settings.AUTH_USER_MODEL)),
                ('recipient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='letter_instances', to='people.person')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LetterEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('created', 'Created'), ('handed_off', 'Handed off'), ('picked_up', 'Picked up'), ('in_transit', 'In transit'), ('left_at_location', 'Left at location'), ('rediscovered', 'Rediscovered'), ('delivered', 'Delivered'), ('archived', 'Archived')], max_length=32)),
                ('occurred_at', models.DateTimeField(auto_now_add=True)),
                ('location_description', models.CharField(blank=True, help_text="Free-text description (e.g., 'XYZ bar, Main St').", max_length=255)),
                ('city', models.CharField(blank=True, max_length=255)),
                ('region', models.CharField(blank=True, max_length=255)),
                ('state', models.CharField(blank=True, max_length=255)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('note', models.TextField(blank=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='letter_events', to=settings.AUTH_USER_MODEL)),
                ('letter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='letters.letterinstance')),
            ],
            options={
                'ordering': ['occurred_at'],
            },
        ),
    ]
