# Generated by Django 6.0 on 2025-12-14 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('letters', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='letterinstance',
            name='body_text',
            field=models.TextField(blank=True, help_text='Digital text of this specific letter, if written online.'),
        ),
    ]
