# Generated by Django 6.0 on 2025-12-14 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('letters', '0002_letterinstance_body_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='letterinstance',
            name='is_public',
            field=models.BooleanField(default=True, help_text='If false, hide this letter body from public reading views.'),
        ),
    ]
