# Generated by Django 6.0 on 2025-12-14 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('letters', '0003_letterinstance_is_public'),
        ('media_app', '0002_remove_mediaitem_event'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='letterconcept',
            name='origin_city',
        ),
        migrations.RemoveField(
            model_name='letterconcept',
            name='origin_region',
        ),
        migrations.RemoveField(
            model_name='letterconcept',
            name='origin_state',
        ),
        migrations.AddField(
            model_name='letterconcept',
            name='destination_social_place_name',
            field=models.CharField(blank=True, help_text='Bar, camp, venue, etc., where this should arrive.', max_length=255),
        ),
        migrations.AddField(
            model_name='letterinstance',
            name='current_social_place_name',
            field=models.CharField(blank=True, help_text='If the letter is left at a specific place (bar, camp, etc.).', max_length=255),
        ),
        migrations.AlterField(
            model_name='letterconcept',
            name='write_prompt',
            field=models.TextField(blank=True, help_text="Optional guidance or script; often same as person's write_about."),
        ),
        migrations.DeleteModel(
            name='LetterEvent',
        ),
    ]
