# Generated by Django 6.0 on 2025-12-14 07:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('letters', '0004_remove_letterconcept_origin_city_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LetterHop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('waiting', 'Waiting to be carried'), ('picked_up', 'Picked up'), ('in_transit', 'In transit'), ('left_at_location', 'Left at location'), ('delivered', 'Delivered'), ('archived', 'Archived')], default='waiting', max_length=20)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('region', models.CharField(blank=True, max_length=100)),
                ('venue_hint', models.CharField(blank=True, help_text='Bar, event, camp, etc.', max_length=255)),
                ('notes', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, upload_to='letter_hops/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('letter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hops', to='letters.letterinstance')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
