# Generated by Django 6.0 on 2025-12-14 03:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(max_length=255)),
                ('city', models.CharField(blank=True, max_length=255)),
                ('region', models.CharField(blank=True, max_length=255)),
                ('state', models.CharField(blank=True, max_length=255)),
                ('write_about', models.TextField(blank=True, help_text='What should people write about for this person?')),
                ('notes_public', models.TextField(blank=True)),
                ('real_name', models.CharField(blank=True, max_length=255)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('postal_address_line1', models.CharField(blank=True, max_length=255)),
                ('postal_address_line2', models.CharField(blank=True, max_length=255)),
                ('postal_city', models.CharField(blank=True, max_length=255)),
                ('postal_state', models.CharField(blank=True, max_length=255)),
                ('postal_postcode', models.CharField(blank=True, max_length=20)),
                ('postal_country', models.CharField(blank=True, max_length=255)),
                ('has_opt_in_postal', models.BooleanField(default=False, help_text='True if person explicitly wants postal fallback used.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='people_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
