# Generated by Django 6.0 on 2025-12-14 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='email',
        ),
        migrations.RemoveField(
            model_name='person',
            name='has_opt_in_postal',
        ),
        migrations.RemoveField(
            model_name='person',
            name='notes_public',
        ),
        migrations.RemoveField(
            model_name='person',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='person',
            name='postal_address_line1',
        ),
        migrations.RemoveField(
            model_name='person',
            name='postal_address_line2',
        ),
        migrations.RemoveField(
            model_name='person',
            name='postal_city',
        ),
        migrations.RemoveField(
            model_name='person',
            name='postal_country',
        ),
        migrations.RemoveField(
            model_name='person',
            name='postal_postcode',
        ),
        migrations.RemoveField(
            model_name='person',
            name='postal_state',
        ),
        migrations.RemoveField(
            model_name='person',
            name='real_name',
        ),
        migrations.AddField(
            model_name='person',
            name='social_place_name',
            field=models.CharField(blank=True, help_text='Bar, camp, venue, event space, etc.', max_length=255),
        ),
        migrations.AlterField(
            model_name='person',
            name='write_about',
            field=models.TextField(blank=True, help_text='Short topic or prompt for this person.'),
        ),
    ]
