# Generated by Django 6.0 on 2025-12-27 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0002_remove_person_email_remove_person_has_opt_in_postal_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
    ]
