# Generated by Django 6.0 on 2025-12-14 03:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('letters', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MediaItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.ImageField(upload_to='letters/')),
                ('kind', models.CharField(choices=[('writer', 'Writer'), ('carrier', 'Carrier'), ('envelope_front', 'Envelope front'), ('envelope_back', 'Envelope back'), ('arrival', 'Arrival'), ('other', 'Other')], default='other', max_length=32)),
                ('captured_at', models.DateTimeField(blank=True, null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('caption', models.TextField(blank=True)),
                ('hashtags', models.CharField(blank=True, help_text="Space or comma separated hashtags like '#piratemail #deadletter'.", max_length=255)),
                ('event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='media_items', to='letters.letterevent')),
                ('letter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media_items', to='letters.letterinstance')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='media_uploaded', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
